[package]
name = "ray-tracing-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
image = "0.23.14"
fastrand = "1.5.0"

[profile.dev]
opt-level = 3               # Use slightly better optimizations.

[profile.release]
debug = true